<?php
/**
 * @file
 * os_blog.pages_default.inc
 */

/**
 * Implementation of hook_default_page_manager_pages().
 */
function os_blog_default_page_manager_pages() {
  $page = new stdClass;
  $page->disabled = FALSE; /* Edit this to true to make a default page disabled initially */
  $page->api_version = 1;
  $page->name = 'blog_administration';
  $page->task = 'page';
  $page->admin_title = 'Blog administration';
  $page->admin_description = '';
  $page->path = 'blog/admin';
  $page->access = array(
    'plugins' => array(
      0 => array(
        'name' => 'perm',
        'settings' => array(
          'perm' => 'administer nodes',
        ),
        'context' => 'logged-in-user',
        'not' => FALSE,
      ),
    ),
    'logic' => 'and',
  );
  $page->menu = array(
    'type' => 'tab',
    'title' => 'Administer blogs',
    'name' => 'navigation',
    'weight' => '42',
    'parent' => array(
      'type' => 'none',
      'title' => '',
      'name' => 'navigation',
      'weight' => '0',
    ),
  );
  $page->arguments = array();
  $page->conf = array(
    'admin_paths' => TRUE,
  );
  $page->default_handlers = array();
  $handler = new stdClass;
  $handler->disabled = FALSE; /* Edit this to true to make a default handler disabled initially */
  $handler->api_version = 1;
  $handler->name = 'page_blog_administration_menu_context';
  $handler->task = 'page';
  $handler->subtask = 'blog_administration';
  $handler->handler = 'menu_context';
  $handler->weight = 0;
  $handler->conf = array(
    'title' => 'Context Admin',
    'no_blocks' => FALSE,
    'css_id' => '',
    'css' => '',
    'contexts' => array(),
    'relationships' => array(),
    'access' => array(
      'logic' => 'and',
    ),
    'context_admin_options' => 'views_bulk_menu',
    'context_admin_vbo_machine_name' => 'blog_admin',
    'context_admin_vbo_views_bulk_node_type' => array(
      'blog' => 'blog',
      'article' => 0,
      'page' => 0,
      'group' => 0,
      'post' => 0,
      'features_test' => 0,
    ),
    'context_admin_vbo_views_bulk_published' => 'both',
  );
  $page->default_handlers[$handler->name] = $handler;
  $pages['blog_administration'] = $page;

 return $pages;

}
